services:
  - type: web
    name: multi-agent-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --cache /tmp/npm-cache --prefer-online --force
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NUMVERIFY_API_KEY
        sync: false  # Set this manually in Render dashboard

  - type: static
    name: multi-agent-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    headers:
      - source: "**"
        headers:
          - key: Cache-Control
            value: no-cache
